theme: jekyll-theme-modernist
name: Andrew Eaton

#Short bio or description (displayed in the header)
description: >
  Welcome to my personal website. I am currently a machine learning fellow in London.
  The main purpose of this website is to provide blog posts on the background of important
  topics in understanding deep learning.

#URL of avatar or profile picture
favicon: "static/images/favicon.ico"
github_username : aweeaton
author_email: aweeaton@gmail.com
layout: post
title: Blog
logo: "static/images/favicon.ico"
markdown: kramdown
footer_links:
  github: aweeaton
aboutme: Hi, this is Andrew.
aboutme_photo: "static/images/mypic.png"
ShowContactInfo: "True"
paginate: 5
