---
#Name of the site (displayed in the header)
name: Andrew Eaton

#Short bio or description (displayed in the header)
description: >
  Welcome to my personal website. I am currently a machine learning fellow in London.
  The main purpose of this website is to provide blog posts on the background of important
  topics in understanding deep learning.

#URL of avatar or profile picture
favicon: https://github.com/aweeaton/aweeaton.github.io/blob/master/static/images/favicon.ico
github_username : aweeaton
author_email: aweeaton@gmail.com
layout: post
title: Blog
logo: https://github.com/aweeaton/aweeaton.github.io/blob/master/static/images/favicon.ico
markdown: kramdown
---
