# Site settings
title: Andrew's Blog
description: Portfolio Website of Andrew Eaton
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Eaton
user_description: I have a background in biology and I am passionate about using deep learning in the fields of medicine and music. I enjoy coding in Python and writing blog posts on the theory behind different concepts in deep learning.
user_title: Machine Learning Fellow
email: aweeaton@gmail.com
twitter_username:
github_username: aweeaton
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
