# Site settings
title: Andrew's Blog
description: Portfolio Website of Andrew Eaton
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Eaton
user_description: I am passionate about applying data science to solve interesting problems. I enjoy writing code in Python and writing blog posts on different data science concepts.
user_title: Master's Student in Data Science at the University of San Francisco 
email: aweeaton@gmail.com
twitter_username:
github_username: aweeaton
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
